-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.

CREATE TABLE IF NOT EXISTS public.alf_api
(
    alfapi_id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    pm_id bigint,
    env_id bigint,
    api_json text COLLATE pg_catalog."default",
    api_date date,
    CONSTRAINT alf_api_pkey PRIMARY KEY (alfapi_id)
);

COMMENT ON TABLE public.alf_api
    IS 'ข้อมูล API alf standard function';

CREATE TABLE IF NOT EXISTS public.alf_contentstore
(
    cont_id bigint NOT NULL,
    pm_id bigint NOT NULL,
    cont_all_kb bigint,
    created_at timestamp with time zone DEFAULT now(),
    cont_year_json text COLLATE pg_catalog."default",
    cont_month_json text COLLATE pg_catalog."default",
    env_id bigint,
    CONSTRAINT alf_contentstore_pkey PRIMARY KEY (cont_id)
);

COMMENT ON COLUMN public.alf_contentstore.pm_id
    IS 'id pm';

COMMENT ON COLUMN public.alf_contentstore.cont_all_kb
    IS 'sizing contentstore ทั้งหมด';

CREATE TABLE IF NOT EXISTS public.customer
(
    cust_id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    cust_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    code character varying(50) COLLATE pg_catalog."default",
    remark text COLLATE pg_catalog."default",
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT customer_pkey PRIMARY KEY (cust_id),
    CONSTRAINT customer_code_key UNIQUE (code)
);

COMMENT ON COLUMN public.customer.code
    IS 'คำย่อ';

CREATE TABLE IF NOT EXISTS public.details_app_content
(
    appcont_id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    pm_id bigint NOT NULL,
    app_size_json text COLLATE pg_catalog."default",
    env_id bigint,
    CONSTRAINT app_details_pkey PRIMARY KEY (appcont_id)
);

COMMENT ON TABLE public.details_app_content
    IS 'รายละเอียด sizing ของโปรแกรมอื่นๆ joget postgresql solr other โดยเก็บเป็น json 
1 json เก็บข้อมูล 1 เดือนที่เช็ควันละรอบ
version workspace (.env)
';

COMMENT ON COLUMN public.details_app_content.app_size_json
    IS 'json ข้อมูล content sizing ระบบอื่นๆรวมกัน เช่น  postgresql data, solr, joget  
1 file มีข้อมูล 1 เดือนที่เก็บข้อมูลทุกวัน';

CREATE TABLE IF NOT EXISTS public.details_pm_site
(
    serv_id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    pm_id bigint NOT NULL,
    serv_name character(50) COLLATE pg_catalog."default",
    serv_ip character(20) COLLATE pg_catalog."default",
    serv_os character(50) COLLATE pg_catalog."default",
    serv_ram_json text COLLATE pg_catalog."default",
    serv_cpu character(20) COLLATE pg_catalog."default",
    created_at timestamp with time zone,
    serv_remark text COLLATE pg_catalog."default",
    env_id bigint,
    hdd_data_json text COLLATE pg_catalog."default",
    ver_alf_json text COLLATE pg_catalog."default",
    ver_postgresql text COLLATE pg_catalog."default",
    alf_transaction_json text COLLATE pg_catalog."default",
    CONSTRAINT details_serv_pkey PRIMARY KEY (serv_id)
);

COMMENT ON TABLE public.details_pm_site
    IS 'รายละเอียด Server  alf api transaction version workspace env และ other';

COMMENT ON COLUMN public.details_pm_site.pm_id
    IS 'ID รอบ PM';

COMMENT ON COLUMN public.details_pm_site.serv_name
    IS 'server name';

COMMENT ON COLUMN public.details_pm_site.serv_cpu
    IS 'จำนวน core cpu';

COMMENT ON COLUMN public.details_pm_site.created_at
    IS 'วันที่กรอกข้อมูล "timestamp"';

COMMENT ON COLUMN public.details_pm_site.serv_remark
    IS 'ข้อสงสัย concern';

CREATE TABLE IF NOT EXISTS public.env
(
    env_id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    env_name character varying(10) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT environment_pkey PRIMARY KEY (env_id)
);

CREATE TABLE IF NOT EXISTS public.pm
(
    pm_id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    cust_id bigint NOT NULL,
    pm_round integer NOT NULL,
    pm_title character varying(255) COLLATE pg_catalog."default" NOT NULL,
    remark text COLLATE pg_catalog."default",
    pm_date date NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    pm_year character(4) COLLATE pg_catalog."default" NOT NULL,
    json_pm boolean DEFAULT false,
    json_alf_api boolean DEFAULT false,
    json_alf_contsize boolean DEFAULT false,
    json_app_size boolean DEFAULT false,
    json_app_api boolean DEFAULT false,
    CONSTRAINT pm_pkey PRIMARY KEY (pm_id)
);

COMMENT ON COLUMN public.pm.cust_id
    IS 'รหัส ID ลูกค้า';

COMMENT ON COLUMN public.pm.pm_round
    IS 'รอบ PM';

COMMENT ON COLUMN public.pm.pm_title
    IS 'ชื่อสัญญาหรือชื่อรอบ PM ';

COMMENT ON COLUMN public.pm.pm_date
    IS 'วันที่ PM';

COMMENT ON COLUMN public.pm.created_at
    IS 'วันที่สร้าง';

ALTER TABLE IF EXISTS public.alf_api
    ADD FOREIGN KEY (pm_id)
    REFERENCES public.pm (pm_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.alf_contentstore
    ADD FOREIGN KEY (pm_id)
    REFERENCES public.pm (pm_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.alf_contentstore
    ADD FOREIGN KEY (env_id)
    REFERENCES public.env (env_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.details_app_content
    ADD FOREIGN KEY (pm_id)
    REFERENCES public.pm (pm_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.details_app_content
    ADD FOREIGN KEY (env_id)
    REFERENCES public.env (env_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.details_pm_site
    ADD FOREIGN KEY (pm_id)
    REFERENCES public.pm (pm_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.details_pm_site
    ADD FOREIGN KEY (env_id)
    REFERENCES public.env (env_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.pm
    ADD FOREIGN KEY (cust_id)
    REFERENCES public.customer (cust_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
