-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.alf_api
(
    alfapi_id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    pm_id bigint NOT NULL,
    env_id bigint NOT NULL,
    api_json text COLLATE pg_catalog."default",
    api_date date,
    CONSTRAINT alf_api_pkey PRIMARY KEY (alfapi_id)
);

COMMENT ON TABLE public.alf_api
    IS 'ข้อมูล API alf standard function';

CREATE TABLE IF NOT EXISTS public.alf_contentstore
(
    cont_id bigint NOT NULL,
    pm_id bigint NOT NULL,
    cont_all_kb bigint,
    created_at timestamp with time zone DEFAULT now(),
    cont_year_json text COLLATE pg_catalog."default",
    cont_month_json text COLLATE pg_catalog."default",
    env_id bigint,
    alf_version_json text COLLATE pg_catalog."default",
    CONSTRAINT alf_contentstore_pkey PRIMARY KEY (cont_id)
);

COMMENT ON COLUMN public.alf_contentstore.pm_id
    IS 'id pm';

COMMENT ON COLUMN public.alf_contentstore.cont_all_kb
    IS 'sizing contentstore ทั้งหมด';

COMMENT ON COLUMN public.alf_contentstore.alf_version_json
    IS 'ข้อมูล json workspace';

CREATE TABLE IF NOT EXISTS public.app_content_sizing
(
    appcont_id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    pm_id bigint NOT NULL,
    app_size_json text COLLATE pg_catalog."default",
    env_id bigint,
    "Year_month_file" character varying(7) COLLATE pg_catalog."default",
    CONSTRAINT app_details_pkey PRIMARY KEY (appcont_id)
);

COMMENT ON TABLE public.app_content_sizing
    IS 'รายละเอียด sizing ของโปรแกรมอื่นๆ joget postgresql solr other โดยเก็บเป็น json 
1 json เก็บข้อมูล 1 เดือนที่เช็ควันละรอบ
version workspace (.env)
';

COMMENT ON COLUMN public.app_content_sizing.app_size_json
    IS 'json ข้อมูล content sizing ระบบอื่นๆรวมกัน เช่น  postgresql data, solr, joget  
1 file มีข้อมูล 1 เดือนที่เก็บข้อมูลทุกวัน';

COMMENT ON COLUMN public.app_content_sizing."Year_month_file"
    IS 'YYYY-MM';

CREATE TABLE IF NOT EXISTS public.app_details
(
    app_id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    pm_id bigint NOT NULL,
    serv_id bigint,
    app_name text COLLATE pg_catalog."default" NOT NULL,
    app_version text COLLATE pg_catalog."default",
    app_path text COLLATE pg_catalog."default",
    created_at timestamp with time zone,
    CONSTRAINT app_pkey PRIMARY KEY (app_id)
);

COMMENT ON TABLE public.app_details
    IS 'สำหรับ application อื่นที่ไม่ใช้ workspace';

COMMENT ON COLUMN public.app_details.app_name
    IS 'รายละเอียด application ที่ติตดั้งโดยข้อมูลเป็น format json 
กรอกเอง ตั้งต้น ชื่อ app/ path folder app/ version app';

COMMENT ON COLUMN public.app_details.app_version
    IS 'version application';

COMMENT ON COLUMN public.app_details.app_path
    IS 'Path install application';

CREATE TABLE IF NOT EXISTS public.app_response
(
    res_id bigint NOT NULL,
    pm_id bigint NOT NULL,
    env_id bigint NOT NULL,
    json_app_response text COLLATE pg_catalog."default",
    year_month_file character varying(7) COLLATE pg_catalog."default",
    CONSTRAINT app_response_pkey PRIMARY KEY (res_id)
);

CREATE TABLE IF NOT EXISTS public.customer
(
    cust_id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    cust_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    cust_code character varying(50) COLLATE pg_catalog."default" NOT NULL,
    project_name text COLLATE pg_catalog."default",
    created_at timestamp with time zone DEFAULT now(),
    cust_desc text COLLATE pg_catalog."default",
    status boolean DEFAULT true,
    CONSTRAINT customer_pkey PRIMARY KEY (cust_id),
    CONSTRAINT customer_code_key UNIQUE (cust_code)
);

COMMENT ON COLUMN public.customer.cust_name
    IS 'ชื่อลูกค้า';

COMMENT ON COLUMN public.customer.cust_code
    IS 'คำย่อลูกค้า';

COMMENT ON COLUMN public.customer.project_name
    IS 'ชื่อโครงการ';

COMMENT ON COLUMN public.customer.cust_desc
    IS 'รายละเอียด อื่นๆ';

COMMENT ON COLUMN public.customer.status
    IS 'สถานะการ support';

CREATE TABLE IF NOT EXISTS public.customer_env
(
    cust_id bigint NOT NULL,
    env_id bigint NOT NULL,
    server_id bigint NOT NULL DEFAULT 0,
    CONSTRAINT customer_env_pkey PRIMARY KEY (cust_id, env_id, server_id)
);

CREATE TABLE IF NOT EXISTS public.env
(
    env_id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    env_name character varying(10) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT environment_pkey PRIMARY KEY (env_id)
);

CREATE TABLE IF NOT EXISTS public.pm_checklist
(
    checklist_id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    json_pm boolean,
    json_alfapi boolean,
    json_api boolean,
    json_size_data boolean,
    pm_id bigint NOT NULL,
    CONSTRAINT pm_checklist_pkey PRIMARY KEY (checklist_id)
);

CREATE TABLE IF NOT EXISTS public.pm_plan
(
    pm_id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    cust_id bigint NOT NULL,
    pm_round integer NOT NULL,
    pm_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    remark text COLLATE pg_catalog."default",
    created_at timestamp with time zone,
    pm_year character(4) COLLATE pg_catalog."default" NOT NULL,
    pm_status boolean NOT NULL DEFAULT false,
    CONSTRAINT pm_pkey PRIMARY KEY (pm_id)
);

COMMENT ON COLUMN public.pm_plan.cust_id
    IS 'รหัส ID ลูกค้า';

COMMENT ON COLUMN public.pm_plan.pm_round
    IS 'รอบ PM';

COMMENT ON COLUMN public.pm_plan.pm_name
    IS 'ชื่อสัญญาหรือชื่อรอบ PM ';

COMMENT ON COLUMN public.pm_plan.created_at
    IS 'วันที่สร้าง';

COMMENT ON COLUMN public.pm_plan.pm_year
    IS 'ปีที่ทำการ PM';

CREATE TABLE IF NOT EXISTS public.pm_round
(
    pm_round_id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at timestamp with time zone,
    env_id bigint NOT NULL,
    json_alf_transact text COLLATE pg_catalog."default",
    json_alf_api_total text COLLATE pg_catalog."default",
    json_alf_api_size text COLLATE pg_catalog."default",
    json_alf_cont_size text COLLATE pg_catalog."default",
    json_ai_response text COLLATE pg_catalog."default",
    pm_id bigint NOT NULL,
    json_workspace text COLLATE pg_catalog."default",
    json_workspace_path text COLLATE pg_catalog."default",
    server_id bigint NOT NULL,
    CONSTRAINT details_serv_pkey PRIMARY KEY (pm_round_id)
);

COMMENT ON TABLE public.pm_round
    IS 'รายละเอียดอื่นๆของการ PM ในรอบนั้นๆ';

COMMENT ON COLUMN public.pm_round.created_at
    IS 'วันที่กรอกข้อมูล "timestamp"';

COMMENT ON COLUMN public.pm_round.json_alf_transact
    IS 'transaction alfresco';

COMMENT ON COLUMN public.pm_round.json_alf_api_total
    IS 'จำนวนไฟล์ทั้งหมดที่ได้จาก API Alfresco';

COMMENT ON COLUMN public.pm_round.json_alf_api_size
    IS 'ขนาดรวมขนาดไฟล์ทั้งหมดด้วย API Alfresco';

COMMENT ON COLUMN public.pm_round.json_alf_cont_size
    IS 'จำนวน Contentstore All ของ Alfresco ';

COMMENT ON COLUMN public.pm_round.json_workspace
    IS 'รายละเอียด Workspace env เช่น version env ';

CREATE TABLE IF NOT EXISTS public.server
(
    serv_id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    env_id bigint NOT NULL,
    pm_id bigint NOT NULL,
    create_at timestamp with time zone NOT NULL,
    cust_id bigint,
    serv_name character varying(200) COLLATE pg_catalog."default",
    serv_os character varying(100) COLLATE pg_catalog."default",
    serv_os_version character varying(100) COLLATE pg_catalog."default",
    serv_ram integer,
    serv_cpu_model_name character varying(100) COLLATE pg_catalog."default",
    serv_cpu_cores integer,
    server_id bigint,
    CONSTRAINT details_server_pkey PRIMARY KEY (serv_id)
);

COMMENT ON COLUMN public.server.pm_id
    IS 'รายละเอียด server spec แบบ json';

COMMENT ON COLUMN public.server.serv_os
    IS 'OS';

COMMENT ON COLUMN public.server.serv_os_version
    IS 'Os version';

COMMENT ON COLUMN public.server.serv_ram
    IS 'จำนวน RAM';

COMMENT ON COLUMN public.server.serv_cpu_cores
    IS 'จำนวน core cpu';

CREATE TABLE IF NOT EXISTS public.server_env
(
    server_id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    server_name character(200) COLLATE pg_catalog."default",
    CONSTRAINT server_pkey PRIMARY KEY (server_id)
);

ALTER TABLE IF EXISTS public.alf_api
    ADD CONSTRAINT alf_api_env_id_fkey FOREIGN KEY (env_id)
    REFERENCES public.env (env_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.alf_api
    ADD CONSTRAINT alf_api_pm_id_fkey FOREIGN KEY (pm_id)
    REFERENCES public.pm_plan (pm_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.alf_contentstore
    ADD CONSTRAINT alf_contentstore_env_id_fkey FOREIGN KEY (env_id)
    REFERENCES public.env (env_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.alf_contentstore
    ADD CONSTRAINT alf_contentstore_pm_id_fkey FOREIGN KEY (pm_id)
    REFERENCES public.pm_plan (pm_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.app_content_sizing
    ADD CONSTRAINT details_app_content_env_id_fkey FOREIGN KEY (env_id)
    REFERENCES public.env (env_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.app_content_sizing
    ADD CONSTRAINT details_app_content_pm_id_fkey FOREIGN KEY (pm_id)
    REFERENCES public.pm_plan (pm_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.app_details
    ADD CONSTRAINT app_id_pm_id_fkey FOREIGN KEY (pm_id)
    REFERENCES public.pm_plan (pm_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.customer_env
    ADD CONSTRAINT customer_env2_id_fkey FOREIGN KEY (env_id)
    REFERENCES public.env (env_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.customer_env
    ADD CONSTRAINT customer_env_id_fkey FOREIGN KEY (cust_id)
    REFERENCES public.customer (cust_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.pm_plan
    ADD CONSTRAINT pm_cust_id_fkey FOREIGN KEY (cust_id)
    REFERENCES public.customer (cust_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.pm_round
    ADD CONSTRAINT details_pm_site_env_id_fkey FOREIGN KEY (env_id)
    REFERENCES public.env (env_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;